sed -i 's/hover:bg-[a-z]*-900\/[0-9]*/hover:bg-primary-soft/g' src/components/*.tsx
sed -i 's/hover:text-[a-z]*-[1-4]00/hover:text-primary/g' src/components/*.tsx
sed -i 's/text-blue-100/text-primary-soft/g' src/components/*.tsx
sed -i 's/text-emerald-100/text-primary-soft/g' src/components/*.tsx
sed -i 's/text-purple-100/text-primary-soft/g' src/components/*.tsx
sed -i 's/text-rose-100/text-primary-soft/g' src/components/*.tsx
sed -i 's/bg-amber-200\/60/bg-primary-soft/g' src/components/*.tsx
sed -i 's/border-amber-100\/50/border-primary-border/g' src/components/*.tsx
sed -i 's/border-indigo-100/border-primary-border/g' src/components/*.tsx
sed -i 's/via-indigo-950/via-primary\/20/g' src/components/*.tsx
sed -i 's/text-indigo-300/text-primary/g' src/components/*.tsx
sed -i 's/text-indigo-400/text-primary/g' src/components/*.tsx
sed -i 's/text-amber-300/text-primary/g' src/components/*.tsx
sed -i 's/text-amber-400/text-primary/g' src/components/*.tsx
sed -i 's/text-emerald-400/text-primary/g' src/components/*.tsx
sed -i 's/text-rose-300/text-primary/g' src/components/*.tsx
sed -i 's/text-rose-400/text-primary/g' src/components/*.tsx
sed -i 's/hover:from-emerald-700/hover:from-primary-hover/g' src/components/*.tsx
sed -i 's/active:bg-blue-800/active:scale-95/g' src/components/*.tsx
sed -i 's/active:bg-emerald-700/active:scale-95/g' src/components/*.tsx
sed -i 's/fill-amber-500/fill-primary/g' src/components/*.tsx
sed -i 's/bg-blue-[0-9]*\/[0-9]*/bg-primary-soft/g' src/components/*.tsx
sed -i 's/bg-emerald-[0-9]*\/[0-9]*/bg-primary-soft/g' src/components/*.tsx
sed -i 's/bg-amber-[0-9]*\/[0-9]*/bg-primary-soft/g' src/components/*.tsx
sed -i 's/bg-rose-[0-9]*\/[0-9]*/bg-primary-soft/g' src/components/*.tsx
